version: '3.7'

services:
  sqlserver-service:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    volumes: 
      - sql_vol:/var/opt/mssql
    ports:
      - "1433:1433"
      - "1434:1434"
      - "443:443"
    networks: 
      - keycloak_net      
    environment:      
      SA_PASSWORD: "SqlServer@123"
      ACCEPT_EULA: "Y"  

  keycloak-service:
    image: jboss/keycloak:latest
    networks: 
      - keycloak_net
    restart: always    
    environment:
      DB_VENDOR: mssql
      DB_ADDR: sqlserver-service
      DB_DATABASE: Keycloak
      DB_USER: sa
      DB_PASSWORD: "SqlServer@123"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - sqlserver-service

networks: 
  keycloak_net:
    driver: bridge

volumes:
  sql_vol:
    driver: local
  keycloak_vol:  
    driver: local  