version: '3.7'

services:
  mongodb:
    image: mongo:4.2.2
    volumes:
      - db_mongo:/data/db
    networks:
      - keycloak_net
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

  keycloak_db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    volumes: 
      - sql_vol:/var/opt/mssql
    ports:
      - "1433:1433"
      - "1434:1434"
      - "443:443"
    networks: 
      - keycloak_net      
    environment:      
      SA_PASSWORD: "SqlServer@123"
      ACCEPT_EULA: "Y"  

  keycloak:
    image: jboss/keycloak:latest
    networks: 
      - keycloak_net
    restart: always    
    volumes:
      - keycloak_vol:/opt/jboss/keycloak/realm-config    
    environment:
      DB_VENDOR: mssql
      DB_ADDR: keycloak_db
      DB_DATABASE: Keycloak
      DB_USER: sa
      DB_PASSWORD: "SqlServer@123"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - keycloak_db

  webapi:
    image: fabricioveronez/pocapi
    build:
      context: src/back/POC
      dockerfile: POC.Api/Dockerfile
    ports:
      - "8383:80"    
    networks:
      - keycloak_net
    environment: 
      MONGODB_CONNECTIONSTRING: mongodb://mongouser:GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY@mongodb:27017/admin
      MONGODB_DATABASE: admin
      IDENTITY_AUTHORITY: http://id.veronez.net/auth/realms/poc
      IDENTITY_AUDIENCE: account
      IDENTITY_METADATAADDRESS: http://id.veronez.net/auth/realms/poc/.well-known/openid-configuration

  webui:  
    image: fabricioveronez/webui:latest      
    build:
      context: src/front
      dockerfile: Dockerfile
    ports:
      - 8181:80       
    depends_on:
      - keycloak  
    networks: 
      - keycloak_net           
    
  nginx:
    image: nginx
    ports: 
     - 80:80
    volumes: 
      - ./nginx.default.conf:/etc/nginx/nginx.conf
    networks: 
      - keycloak_net    
    depends_on:
      - keycloak    
      - webui       

networks: 
  keycloak_net:
    driver: bridge

volumes:
  sql_vol:
    driver: local
  keycloak_vol:  
    driver: local  
  db_mongo:
    driver: local  
