version: '3.4'

services:
  mongodb:
    image: mongo:4.2.2
    ports: 
      - "27017:27017"
    volumes:
      - db_mongo:/data/db
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

volumes:
  db_mongo: 
